### ISSUE TITLE
`make html` fails on macOS 10.12 due to conda-installed curl

### ISSUE THREAD

**Issue by thermokarst** [qiime2/docs#45]
The `r` packages installed as part of bootstrapping a QIIME2 environment apparently have a `curl` requirement. It looks like the recipe uses my system-installed curl, but, conda rewrites the certs path. Running `make html` with the `-s` removed on a curl command:

```sh
Extension error:
Command 'curl https://codeload.github.com/qiime2/q2studio/zip/0.0.6 -o q2studio-0.0.6.zip' exited with non-zero return code 77.

stdout:



stderr:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  curl: (77) error setting certificate verify locations:
  CAfile: /Users/matthew/miniconda3/envs/q206/etc/pki/tls/certs/cacert.pem
  CApath: none
```

We have had a few `curl`-related issues pop up lately, maybe it is worth looking at `wget` instead?

**Comment by jakereps** [comment]
That's so strange, just like Daniel's problem with `curl`, this is working fine for me on Version 10.12.1 (16B2659). I think the tutorials were `wget` up until SciPy, but it was dropped just because it doesn't come with Macs.


![image](https://cloud.githubusercontent.com/assets/2638727/21033647/203976ca-bd6f-11e6-9765-fa725d8d1a46.png)

```
(qiime2) [17:56] ~ $ which curl
/Users/jakereps/Developer/miniconda3/envs/qiime2/bin/curl
(qiime2) [17:56] ~ $ curl --version
curl 7.49.0 (x86_64-apple-darwin11.4.2) libcurl/7.49.0 OpenSSL/1.0.2j zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
```

**Comment by thermokarst** [comment]
Yep, just like what @wasade reported! Just to clarify though, this isn't about a specific `curl` version (I'm on 7.49.1), this has to do with the conda-supplied curl package overriding some of the configuration settings for my system-install.

**Comment by thermokarst** [comment]
This just came up this evening: https://forum.qiime2.org/t/curl-sl-not-working-on-my-mac-when-following-the-tutorial/170

**Comment by jairideout** [comment]
@thermokarst, @ebolyen, and I talked about curl alternatives. We were thinking that instead of displaying explicit download commands to users, we use a custom download directive that uses wget to download files, but this command isn't displayed to users in the built docs. This hidden download command would be used to automate running of the tutorials (e.g. with `make html`). It seems reasonable that a dev building the docs will have (or can obtain) wget.

In the built docs, the download directive would display text describing different options for downloading the file. For example, download from within browser, wget, curl, etc.

It just doesn't seem feasible to have a download command that works out-of-the-box for all users on *nix and OS X.
