### ISSUE TITLE
Read-Joining tutorial data in outdated SingleEndFastqManifestPhred33 format

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/docs#460]
**Bug Description**
Our "alternative methods of read-joining" tutorial data is still in `SingleEndFastqManifestPhred33` format, and should probably be updated to `SingleEndFastqManifestPhred33V2` to prevent unnecessary confusion.

**Steps to reproduce the behavior**
1. Go to https://docs.qiime2.org/2018.4/tutorials/read-joining/#importing-pre-joined-reads
2. Download `jf-joined.zip`
3. Open the manifest and confirm format is old.

**Expected behavior**
Manifest formatted in V2

**Comments**
1. The OP that raised this issue on the forum was having trouble because they passed the wrong format name to `--input-format`, but they did a great job showing how much confusion can result from hosting inconsistent formats across tutorials. 

**References**
[forum xref](https://forum.qiime2.org/t/problems-about-analyzing-joined-reads-using-qiime2/14950)

**Comment by thermokarst** [comment]
> Go to https://docs.qiime2.org/2018.4/tutorials/read-joining/#importing-pre-joined-reads

Whoa, 2018.4, that's a blast from the past.

---

Sometimes its less work to just open a PR ([link](https://github.com/qiime2/docs/pull/461)), rather than write out the whole issue, this is a pretty good case for that.

FWIW - the CSV format is still valid, and supported - I don't think we necessarily _need_ to update the format, there are other ways we could provide education (for example - the _Import Wizard_ that y'all worked on last semester would be a great tool to help guide folks through situations like this.)
