### ISSUE TITLE
Following installation instructions results in wget error on macOS

### ISSUE THREAD

**Issue by colinvwood** [qiime2/docs#570]
Following the [native installation instructions](https://docs.qiime2.org/2023.9/install/native/) fails at the `wget <link to env file>` step with the following error:

```
dyld[62076]: Library not loaded: @rpath/libidn2.0.dylib
  Referenced from: <1705387D-7F87-387E-9EAF-B86871B2FEF2> /Users/colinwood/miniconda3/bin/wget
  Reason: tried: '/Users/colinwood/miniconda3/bin/../lib/libidn2.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/colinwood/miniconda3/bin/../lib/libidn2.0.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/usr/local/lib/libidn2.0.dylib' (no such file), '/usr/lib/libidn2.0.dylib' (no such file, not in dyld cache)
zsh: abort      wget 
```

All previous steps succeed. This happens for me on two different M1 machines, one running Sonoma 14.1.2 and one running Ventura 13.2.1. Failures occur with a freshly installed Miniconda environment, as the docs suggest. 

Updating the instructions to use `curl -L -O <link to env file>` instead of `wget <link to env file>` is a possible solution.

**Comment by cherman2** [comment]
I think this is a M1 specific error, I tested it on my machine and I had no problem. I have a non-M1 Mac

**Comment by lizgehret** [comment]
Hey @colinvwood, has `wget` ever worked on your machine? If so, did you update your OS recently?

**Comment by gregcaporaso** [comment]
I have an M1 mac, and just tested - the Native Install Instructions for macOS (Apple Silicon) are working for me.

**Comment by colinvwood** [comment]
Hey @lizgehret wget installed via conda has worked in the past but not for a while for me.

That's interesting @gregcaporaso yeah I guess I figure we would have seen this on the forum if it were affecting more people. Once I had it happen on different machine I thought it was worth an issue though.

**Comment by lizgehret** [comment]
@colinvwood hmm that's interesting. I remember you had some issues with conda a while back when we were sorting through the conda vs mamba install - was it around that time? I'm wondering if you may want to just try installing wget via pip in your base env (since I don't think it particularly matters how wget is installed for qiime2 env stuff).

I did find one anecdotal SO post where someone with an M1 mac mentioned having to go through some circuitous install steps for wget, but I couldn't find any additional information on that, so not sure how reliable that is.

**Comment by gregcaporaso** [comment]
I installed `wget` on my M1 mac with Homebrew (ages ago), and that appears to still be the version that is used from my base conda environment.
